package edu.southern.pointcloud.export

import edu.southern.pointcloud.data.models.Point3D
import java.io.BufferedOutputStream
import java.io.File
import java.io.FileOutputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Writes a binary little-endian PLY file — the format SketchUp and MeshLab
 * open natively without any plugin.
 *
 * Property order: x y z r g b (float32 × 3, uint8 × 3 = 15 bytes/point)
 */
object PlyExporter {

    fun export(points: List<Point3D>, outFile: File, onProgress: (Int) -> Unit = {}) {
        outFile.parentFile?.mkdirs()
        val n = points.size

        BufferedOutputStream(FileOutputStream(outFile), 256 * 1024).use { out ->
            // ASCII header
            val header = buildString {
                appendLine("ply")
                appendLine("format binary_little_endian 1.0")
                appendLine("comment Generated by PointCloudScanner for Samsung S26 Ultra")
                appendLine("element vertex $n")
                appendLine("property float x")
                appendLine("property float y")
                appendLine("property float z")
                appendLine("property uchar red")
                appendLine("property uchar green")
                appendLine("property uchar blue")
                appendLine("end_header")
            }
            out.write(header.toByteArray(Charsets.US_ASCII))

            // Binary point records
            val buf = ByteBuffer.allocate(15 * 8192).order(ByteOrder.LITTLE_ENDIAN)
            var reported = 0

            for ((i, p) in points.withIndex()) {
                buf.putFloat(p.x)
                buf.putFloat(p.y)
                buf.putFloat(p.z)
                buf.put(p.r)
                buf.put(p.g)
                buf.put(p.b)

                if (!buf.hasRemaining()) {
                    out.write(buf.array(), 0, buf.position())
                    buf.clear()
                }

                val progress = (i + 1) * 100 / n
                if (progress != reported) { reported = progress; onProgress(progress) }
            }

            if (buf.position() > 0) {
                out.write(buf.array(), 0, buf.position())
            }
        }
    }
}
